spring.application.name=SecureLearn
spring.datasource.url= jdbc:postgresql://localhost:5432/SecureLearn
spring.datasource.username=postgres
spring.datasource.password=12345
spring:
    security:
        oauth2:
            client:
                registration:
                    cognito:
                        client-id: 6dfhhe4nbsb5m1rrujnvsf08rm
                        client-secret: <client secret>
                        scope:
                        - email
                        - openid
                        - phone
                        # Spring Security by default uses a redirect-uri in the format: {baseUrl}/login/oauth2/code/{registrationId}
                        # For example: http://localhost:8080/login/oauth2/code/cognito
                        # See more: https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-sample-redirect-uri
                        redirect-uri: http://localhost:3000
                provider:
                    cognito:
                        issuerUri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_ZlYH5RGBn
                        user-name-attribute: username
